### ISSUE TITLE
win 11下安装包不能运行

### ISSUE THREAD

**Issue by dosong123** [vannvan/rust-explore#1]
下载ytool-Windows-x86_64.zip后，解压的 ytool.exe无法正常运行
双击后，没有正常启动可执行问题

**Comment by vannvan** [comment]
> 下载ytool-Windows-x86_64.zip后，解压的 ytool.exe无法正常运行 双击后，没有正常启动可执行问题

不是双击，是在程序所在目录下采用终端去执行的，but，很遗憾语雀目前登录机制调整了，整个程序暂时也不可用了，需要一些时间去破解

**Comment by vannvan** [comment]
已解决

**Comment by niko349** [comment]
不一定需要登录吧？设置cookies不行吗？

**Comment by vannvan** [comment]
> 不一定需要登录吧？设置cookies不行吗？

登录其实主要就是为了获取cookies，但因为同时也支持获取账户下协作知识库，交互需要对个人知识库和协作知识库进行区分，所以还是需要登录才能做到

**Comment by hirolee88** [comment]
> 协作知识库，交互需要对个人知识库和协作知识库进行区分，所以还是需要登录才能做到

现在不能用了吗

**Comment by vannvan** [comment]
> > 协作知识库，交互需要对个人知识库和协作知识库进行区分，所以还是需要登录才能做到
> 
> 现在不能用了吗？ [#2 (comment)](https://github.com/vannvan/rust-explore/issues/2#issue-2051903675)

如果是导出知识库要用pull命令，grd命令是用来导出团队资源的

**Comment by hirolee88** [comment]
> > > 协作知识库，交互需要对个人知识库和协作知识库进行区分，所以还是需要登录才能做到
> > 
> > 
> > 现在不能用了吗？ [#2 (comment)](https://github.com/vannvan/rust-explore/issues/2#issue-2051903675)
> 
> 如果是导出知识库要用pull命令，grd命令是用来导出团队资源的

是要导团队的。团队资源下载任务完成，共下载0个文件  完了resource目录是空的

**Comment by vannvan** [comment]
> > > > 协作知识库，交互需要对个人知识库和协作知识库进行区分，所以还是需要登录才能做到
> > > 
> > > 
> > > 现在不能用了吗？ [#2 (comment)](https://github.com/vannvan/rust-explore/issues/2#issue-2051903675)
> > 
> > 
> > 如果是导出知识库要用pull命令，grd命令是用来导出团队资源的
> 
> 是要导团队的。团队资源下载任务完成，共下载0个文件 完了resource目录是空的

方便的话加一下我vx https://github.com/vannvan/yuque-tools/issues/15
